# -*- coding: utf-8 -*-

"""
Script to plot a comparison between a baseline model and a candidate model
using prediction interval CSV outputs generated by the pipeline.
"""

import argparse
import sys
from pathlib import Path

# Ensure project root is on PYTHONPATH when running as a script
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(PROJECT_ROOT))

from _utils.plots import plot_comparison_with_baseline


def main():
    parser = argparse.ArgumentParser(
        description="Plot forecast comparison with prediction intervals"
    )

    parser.add_argument(
        "--baseline",
        type=str,
        required=True,
        help="Path to baseline CSV (e.g. output/predictions/pis/direct_SARIMAX_h6_with_PI.csv)"
    )

    parser.add_argument(
        "--compare",
        type=str,
        required=True,
        help="Path to model CSV to compare (e.g. output/predictions/pis/stage2_ARIMA_Linear_h6_with_PI.csv)"
    )

    parser.add_argument(
        "--pi",
        type=int,
        default=95,
        choices=[80, 95],
        help="Prediction interval level (80 or 95). Default: 95"
    )

    parser.add_argument(
        "--title",
        type=str,
        default=None,
        help="Optional custom title for the figure"
    )

    args = parser.parse_args()

    plot_comparison_with_baseline(
        baseline_file=args.baseline,
        compare_file=args.compare,
        pi=args.pi,
        title=args.title
    )


if __name__ == "__main__":
    main()